#!/bin/bash
# Script to create git server repository

name=$1
path=$2
cdir=$(pwd)

echo $0" => Debug name: "$name", path: "$path", cdir: "$cdir

#
if [[ "$name" == "" ]]; then
    echo $0" => Usage: "$0" new_repo_name.git"
    exit
fi
#
if [[ "$path" == "" ]]; then
    path="/home/git/"
fi
#
echo $0" => Creating repository at "$path$name
mkdir $path$name
cd $path$name
git init --bare
chown -R git.git $path$name
cd $cdir
echo $0" => Done!"
