#!/bin/bash
# gmd-gui - Graphical user interface for GMD (LoK wrapper)
# Accessible as: lok GIT gmd-gui RUN or directly as gmd-gui
# Auto-generated by src/submodule-generate.sh

PRE=$(dirname $(realpath $0))"/../"
source $PRE'src/prepare.sh'
source $PRE'src/history.sh'
source $PRE'src/submodule.sh'

SM_PATH="$PRE/GIT/gmd"
SN="gmd-gui"

PCA=()

PCA_ON_NONE_HELP=false


# Special flags handled before PCA
for arg in "$@"; do
	case "$arg" in
		-HH|--HH)
			history_init "$SN"
			history_list
			exit 0
			;;
		--tool-help)
			if submodule_check "$SM_PATH"; then
				export PYTHONPATH="$SM_PATH:$PYTHONPATH"
				exec python3 "$SM_PATH/scripts/gmd-gui" --help
			else
				echo "Error: Submodule 'gmd' is not installed." >&2
				exit 1
			fi
			;;
	esac
done

source $PRE'src/pca.sh'

# Check if submodule is installed
if ! submodule_check "$SM_PATH"; then
	submodule_get_config "$SM_PATH" 2>/dev/null
	submodule_prompt "${SM_NAME:-gmd}" "${SM_URL:-https://github.com/m5it/gmd.git}" "$SM_PATH"
	[[ $? -ne 0 ]] && exit 1
	if ! submodule_check "$SM_PATH"; then
		echo "Error: Submodule still not available after install attempt." >&2
		exit 1
	fi
fi

# Build args from PCA variables
ARGS=()

# Also pass any raw arguments from command line (direct invocation, non-PCA flags)
if [[ ${#PCA[@]} -eq 0 ]]; then
	for arg in "$@"; do
		case "$arg" in
			-RR|-Y|--run_config) continue ;;
			*) ARGS+=("$arg") ;;
		esac
	done
fi

# Initialize history
livedir="$DL/GIT/$SN"
livefile="$livedir/config"
if [[ ! -d "$livedir" ]]; then
	mkdir -p "$livedir"
fi

: > "$livefile"

history_init "$SN"
tmpdata=$(concat_lines "$livefile")
[[ -n "$tmpdata" ]] && history_add "$tmpdata"

# Execute the actual command
export PYTHONPATH="$SM_PATH:$PYTHONPATH"
python3 "$SM_PATH/scripts/gmd-gui" "${ARGS[@]}"
exit $?
