#!/bin/bash
# fwspoof - Detect and block SYN flood and SYN+RESET spoofing attacks from tcpdump captures (LoK wrapper)
# Accessible as: lok FW fwspoof RUN or directly as fwspoof
# Auto-generated by src/submodule-generate.sh

PRE=$(dirname $(realpath $0))"/../"
source $PRE'src/prepare.sh'
source $PRE'src/history.sh'
source $PRE'src/submodule.sh'

SM_PATH="$PRE/FW/fwspoof"
SN="fwspoof"

PCA=("MAX_FLAG_COUNT" "MAX_FLAG_COUNT_PER_CIDR" "MAX_FLAG_COUNT_PER_CIDR_SR" "VERBOSE" "STATS" "FLAGS" "CON_TYPE" "DONT_UNBLOCK" "TEST" "SPECIFIC_IP" "CONFIG" "ALLOWED_IPS" "VERSION" )

PCA_ON_NONE_HELP=false

ARG_MAX_FLAG_COUNT=""
ARG_MAX_FLAG_COUNT_STRING=true
MAX_FLAG_COUNT_SHORT_ARG="-M"
MAX_FLAG_COUNT_ARG="--max-flag-count"
MAX_FLAG_COUNT_VAL=true

ARG_MAX_FLAG_COUNT_PER_CIDR=""
ARG_MAX_FLAG_COUNT_PER_CIDR_STRING=true
MAX_FLAG_COUNT_PER_CIDR_SHORT_ARG="-m"
MAX_FLAG_COUNT_PER_CIDR_ARG="--max-flag-count-per-cidr"
MAX_FLAG_COUNT_PER_CIDR_VAL=true

ARG_MAX_FLAG_COUNT_PER_CIDR_SR=""
ARG_MAX_FLAG_COUNT_PER_CIDR_SR_STRING=true
MAX_FLAG_COUNT_PER_CIDR_SR_SHORT_ARG="-r"
MAX_FLAG_COUNT_PER_CIDR_SR_ARG="--max-flag-count-per-cidr-sr"
MAX_FLAG_COUNT_PER_CIDR_SR_VAL=true

ARG_VERBOSE=false
ARG_VERBOSE_STRING=true
VERBOSE_SHORT_ARG="-V"
VERBOSE_ARG="--verbose"
VERBOSE_VAL=false

ARG_STATS=false
ARG_STATS_STRING=true
STATS_SHORT_ARG="-S"
STATS_ARG="--stats"
STATS_VAL=false

ARG_FLAGS=""
ARG_FLAGS_STRING=true
FLAGS_SHORT_ARG="-F"
FLAGS_ARG="--flags"
FLAGS_VAL=true

ARG_CON_TYPE=""
ARG_CON_TYPE_STRING=true
CON_TYPE_SHORT_ARG="-C"
CON_TYPE_ARG="--con-type"
CON_TYPE_VAL=true

ARG_DONT_UNBLOCK=false
ARG_DONT_UNBLOCK_STRING=true
DONT_UNBLOCK_SHORT_ARG="-D"
DONT_UNBLOCK_ARG="--dont-unblock"
DONT_UNBLOCK_VAL=false

ARG_TEST=false
ARG_TEST_STRING=true
TEST_SHORT_ARG="-T"
TEST_ARG="--test"
TEST_VAL=false

ARG_SPECIFIC_IP=false
ARG_SPECIFIC_IP_STRING=true
SPECIFIC_IP_SHORT_ARG="-s"
SPECIFIC_IP_ARG="--specific-ip"
SPECIFIC_IP_VAL=false

ARG_CONFIG=""
ARG_CONFIG_STRING=true
CONFIG_SHORT_ARG="-c"
CONFIG_ARG="--config"
CONFIG_VAL=true

ARG_ALLOWED_IPS=""
ARG_ALLOWED_IPS_STRING=true
ALLOWED_IPS_SHORT_ARG="-a"
ALLOWED_IPS_ARG="--allowed-ips"
ALLOWED_IPS_VAL=true

ARG_VERSION=false
ARG_VERSION_STRING=true
VERSION_SHORT_ARG="-v"
VERSION_ARG="--version"
VERSION_VAL=false
# Special flags handled before PCA
for arg in "$@"; do
	case "$arg" in
		-HH|--HH)
			history_init "$SN"
			history_list
			exit 0
			;;
		--tool-help)
			if submodule_check "$SM_PATH"; then
				export PYTHONPATH="$SM_PATH:$PYTHONPATH"
				exec python3 "$SM_PATH/main.py" --help
			else
				echo "Error: Submodule 'fwspoof' is not installed." >&2
				exit 1
			fi
			;;
	esac
done

source $PRE'src/pca.sh'

# Check if submodule is installed
if ! submodule_check "$SM_PATH"; then
	submodule_get_config "$SM_PATH" 2>/dev/null
	submodule_prompt "${SM_NAME:-fwspoof}" "${SM_URL:-https://github.com/m5it/fwspoof.git}" "$SM_PATH"
	[[ $? -ne 0 ]] && exit 1
	if ! submodule_check "$SM_PATH"; then
		echo "Error: Submodule still not available after install attempt." >&2
		exit 1
	fi
fi

# Build args from PCA variables
ARGS=()
[[ -n "$ARG_MAX_FLAG_COUNT" ]] && ARGS+=("-M" "$ARG_MAX_FLAG_COUNT")
[[ -n "$ARG_MAX_FLAG_COUNT_PER_CIDR" ]] && ARGS+=("-m" "$ARG_MAX_FLAG_COUNT_PER_CIDR")
[[ -n "$ARG_MAX_FLAG_COUNT_PER_CIDR_SR" ]] && ARGS+=("-r" "$ARG_MAX_FLAG_COUNT_PER_CIDR_SR")
[[ "$ARG_VERBOSE" == "true" ]] && ARGS+=("-V")
[[ "$ARG_STATS" == "true" ]] && ARGS+=("-S")
[[ -n "$ARG_FLAGS" ]] && ARGS+=("-F" "$ARG_FLAGS")
[[ -n "$ARG_CON_TYPE" ]] && ARGS+=("-C" "$ARG_CON_TYPE")
[[ "$ARG_DONT_UNBLOCK" == "true" ]] && ARGS+=("-D")
[[ "$ARG_TEST" == "true" ]] && ARGS+=("-T")
[[ "$ARG_SPECIFIC_IP" == "true" ]] && ARGS+=("-s")
[[ -n "$ARG_CONFIG" ]] && ARGS+=("-c" "$ARG_CONFIG")
[[ -n "$ARG_ALLOWED_IPS" ]] && ARGS+=("-a" "$ARG_ALLOWED_IPS")
[[ "$ARG_VERSION" == "true" ]] && ARGS+=("-v")
# Also pass any raw arguments from command line (direct invocation, non-PCA flags)
if [[ ${#PCA[@]} -eq 0 ]]; then
	for arg in "$@"; do
		case "$arg" in
			-RR|-Y|--run_config) continue ;;
			*) ARGS+=("$arg") ;;
		esac
	done
fi

# Initialize history
livedir="$DL/FW/$SN"
livefile="$livedir/config"
if [[ ! -d "$livedir" ]]; then
	mkdir -p "$livedir"
fi

: > "$livefile"
[[ -n "$ARG_MAX_FLAG_COUNT" ]] && echo "MAX_FLAG_COUNT:$ARG_MAX_FLAG_COUNT" >> "$livefile"
[[ -n "$ARG_MAX_FLAG_COUNT_PER_CIDR" ]] && echo "MAX_FLAG_COUNT_PER_CIDR:$ARG_MAX_FLAG_COUNT_PER_CIDR" >> "$livefile"
[[ -n "$ARG_MAX_FLAG_COUNT_PER_CIDR_SR" ]] && echo "MAX_FLAG_COUNT_PER_CIDR_SR:$ARG_MAX_FLAG_COUNT_PER_CIDR_SR" >> "$livefile"
[[ "$ARG_VERBOSE" == "true" ]] && echo "VERBOSE:true" >> "$livefile"
[[ "$ARG_STATS" == "true" ]] && echo "STATS:true" >> "$livefile"
[[ -n "$ARG_FLAGS" ]] && echo "FLAGS:$ARG_FLAGS" >> "$livefile"
[[ -n "$ARG_CON_TYPE" ]] && echo "CON_TYPE:$ARG_CON_TYPE" >> "$livefile"
[[ "$ARG_DONT_UNBLOCK" == "true" ]] && echo "DONT_UNBLOCK:true" >> "$livefile"
[[ "$ARG_TEST" == "true" ]] && echo "TEST:true" >> "$livefile"
[[ "$ARG_SPECIFIC_IP" == "true" ]] && echo "SPECIFIC_IP:true" >> "$livefile"
[[ -n "$ARG_CONFIG" ]] && echo "CONFIG:$ARG_CONFIG" >> "$livefile"
[[ -n "$ARG_ALLOWED_IPS" ]] && echo "ALLOWED_IPS:$ARG_ALLOWED_IPS" >> "$livefile"
[[ "$ARG_VERSION" == "true" ]] && echo "VERSION:true" >> "$livefile"
history_init "$SN"
tmpdata=$(concat_lines "$livefile")
[[ -n "$tmpdata" ]] && history_add "$tmpdata"

# Execute the actual command
export PYTHONPATH="$SM_PATH:$PYTHONPATH"
python3 "$SM_PATH/main.py" "${ARGS[@]}"
exit $?
