#!/bin/bash
# fwtrash - Modern security log analyzer with real-time threat detection and automatic IP blocking (LoK wrapper)
# Accessible as: lok FW fwtrash RUN or directly as fwtrash
# Auto-generated by src/submodule-generate.sh

PRE=$(dirname $(realpath $0))"/../"
source $PRE'src/prepare.sh'
source $PRE'src/history.sh'
source $PRE'src/submodule.sh'

SM_PATH="$PRE/FW/fwtrash"
SN="fwtrash"

PCA=("VERBOSE" "QUIET" "RULES" "PARSER" "BADIPS" "TRASH" "ALLOWED" "COMMAND" "DRY_RUN" "STAT_KEYS" "STAT_TEMPLATE" "DISABLE_STATS" "STOP_NEXT_DAY" "AUTOSAVE" "DASHBOARD" "DASHBOARD_PORT" "LEGACY_MODE" "VERSION" )

PCA_ON_NONE_HELP=true

ARG_VERBOSE=false
ARG_VERBOSE_STRING=true
VERBOSE_SHORT_ARG="-v"
VERBOSE_ARG="--verbose"
VERBOSE_VAL=false

ARG_QUIET=false
ARG_QUIET_STRING=true
QUIET_SHORT_ARG="-q"
QUIET_ARG="--quiet"
QUIET_VAL=false

ARG_RULES=""
ARG_RULES_STRING=true
RULES_SHORT_ARG="-P"
RULES_ARG="--rules"
RULES_VAL=true

ARG_PARSER=""
ARG_PARSER_STRING=true
PARSER_SHORT_ARG="-p"
PARSER_ARG="--parser"
PARSER_VAL=true

ARG_BADIPS=""
ARG_BADIPS_STRING=true
BADIPS_SHORT_ARG="-o"
BADIPS_ARG="--badips"
BADIPS_VAL=true

ARG_TRASH=""
ARG_TRASH_STRING=true
TRASH_SHORT_ARG="-O"
TRASH_ARG="--trash"
TRASH_VAL=true

ARG_ALLOWED=""
ARG_ALLOWED_STRING=true
ALLOWED_SHORT_ARG="-a"
ALLOWED_ARG="--allowed"
ALLOWED_VAL=true

ARG_COMMAND=""
ARG_COMMAND_STRING=true
COMMAND_SHORT_ARG="-c"
COMMAND_ARG="--command"
COMMAND_VAL=true

ARG_DRY_RUN=false
ARG_DRY_RUN_STRING=true
DRY_RUN_SHORT_ARG="-n"
DRY_RUN_ARG="--dry-run"
DRY_RUN_VAL=false

ARG_STAT_KEYS=""
ARG_STAT_KEYS_STRING=true
STAT_KEYS_SHORT_ARG="-s"
STAT_KEYS_ARG="--stat-keys"
STAT_KEYS_VAL=true

ARG_STAT_TEMPLATE=""
ARG_STAT_TEMPLATE_STRING=true
STAT_TEMPLATE_SHORT_ARG="-S"
STAT_TEMPLATE_ARG="--stat-template"
STAT_TEMPLATE_VAL=true

ARG_DISABLE_STATS=false
ARG_DISABLE_STATS_STRING=true
DISABLE_STATS_SHORT_ARG="-d"
DISABLE_STATS_ARG="--disable-stats"
DISABLE_STATS_VAL=false

ARG_STOP_NEXT_DAY=false
ARG_STOP_NEXT_DAY_STRING=true
STOP_NEXT_DAY_SHORT_ARG="-D"
STOP_NEXT_DAY_ARG="--stop-next-day"
STOP_NEXT_DAY_VAL=false

ARG_AUTOSAVE=""
ARG_AUTOSAVE_STRING=true
AUTOSAVE_ARG="--autosave"
AUTOSAVE_VAL=true

ARG_DASHBOARD=false
ARG_DASHBOARD_STRING=true
DASHBOARD_ARG="--dashboard"
DASHBOARD_VAL=false

ARG_DASHBOARD_PORT=""
ARG_DASHBOARD_PORT_STRING=true
DASHBOARD_PORT_ARG="--dashboard-port"
DASHBOARD_PORT_VAL=true

ARG_LEGACY_MODE=false
ARG_LEGACY_MODE_STRING=true
LEGACY_MODE_ARG="--legacy-mode"
LEGACY_MODE_VAL=false

ARG_VERSION=false
ARG_VERSION_STRING=true
VERSION_SHORT_ARG="-V"
VERSION_ARG="--version"
VERSION_VAL=false
# Special flags handled before PCA
for arg in "$@"; do
	case "$arg" in
		-HH|--HH)
			history_init "$SN"
			history_list
			exit 0
			;;
		--tool-help)
			if submodule_check "$SM_PATH"; then
				PYTHON="$SM_PATH/v2/.venv/bin/python3"
				if [[ -x "$PYTHON" ]]; then
					exec $PYTHON -m fwtrash.cli.main run --help
				else
					echo "Error: Virtual environment not found at $SM_PATH/v2/.venv" >&2
					exit 1
				fi
			else
				echo "Error: Submodule 'fwtrash' is not installed." >&2
				exit 1
			fi
			;;
	esac
done

source $PRE'src/pca.sh'

# Check if submodule is installed
if ! submodule_check "$SM_PATH"; then
	submodule_get_config "$SM_PATH" 2>/dev/null
	submodule_prompt "${SM_NAME:-fwtrash}" "${SM_URL:-https://github.com/grandekos/fwtrash.git}" "$SM_PATH"
	[[ $? -ne 0 ]] && exit 1
	if ! submodule_check "$SM_PATH"; then
		echo "Error: Submodule still not available after install attempt." >&2
		exit 1
	fi
fi

# Build args from PCA variables
ARGS=()
[[ "$ARG_VERBOSE" == "true" ]] && ARGS+=("-v")
[[ "$ARG_QUIET" == "true" ]] && ARGS+=("-q")
[[ -n "$ARG_RULES" ]] && ARGS+=("-P" "$ARG_RULES")
[[ -n "$ARG_PARSER" ]] && ARGS+=("-p" "$ARG_PARSER")
[[ -n "$ARG_BADIPS" ]] && ARGS+=("-o" "$ARG_BADIPS")
[[ -n "$ARG_TRASH" ]] && ARGS+=("-O" "$ARG_TRASH")
[[ -n "$ARG_ALLOWED" ]] && ARGS+=("-a" "$ARG_ALLOWED")
[[ -n "$ARG_COMMAND" ]] && ARGS+=("-c" "$ARG_COMMAND")
[[ "$ARG_DRY_RUN" == "true" ]] && ARGS+=("-n")
[[ -n "$ARG_STAT_KEYS" ]] && ARGS+=("-s" "$ARG_STAT_KEYS")
[[ -n "$ARG_STAT_TEMPLATE" ]] && ARGS+=("-S" "$ARG_STAT_TEMPLATE")
[[ "$ARG_DISABLE_STATS" == "true" ]] && ARGS+=("-d")
[[ "$ARG_STOP_NEXT_DAY" == "true" ]] && ARGS+=("-D")
[[ -n "$ARG_AUTOSAVE" ]] && ARGS+=("--autosave" "$ARG_AUTOSAVE")
[[ "$ARG_DASHBOARD" == "true" ]] && ARGS+=("--dashboard")
[[ -n "$ARG_DASHBOARD_PORT" ]] && ARGS+=("--dashboard-port" "$ARG_DASHBOARD_PORT")
[[ "$ARG_LEGACY_MODE" == "true" ]] && ARGS+=("--legacy-mode")
[[ "$ARG_VERSION" == "true" ]] && ARGS+=("-V")
# Also pass any raw arguments from command line (direct invocation, non-PCA flags)
if [[ ${#PCA[@]} -eq 0 ]]; then
	for arg in "$@"; do
		case "$arg" in
			-RR|-Y|--run_config) continue ;;
			*) ARGS+=("$arg") ;;
		esac
	done
fi

# Initialize history
livedir="$DL/FW/$SN"
livefile="$livedir/config"
if [[ ! -d "$livedir" ]]; then
	mkdir -p "$livedir"
fi

: > "$livefile"
[[ "$ARG_VERBOSE" == "true" ]] && echo "VERBOSE:true" >> "$livefile"
[[ "$ARG_QUIET" == "true" ]] && echo "QUIET:true" >> "$livefile"
[[ -n "$ARG_RULES" ]] && echo "RULES:$ARG_RULES" >> "$livefile"
[[ -n "$ARG_PARSER" ]] && echo "PARSER:$ARG_PARSER" >> "$livefile"
[[ -n "$ARG_BADIPS" ]] && echo "BADIPS:$ARG_BADIPS" >> "$livefile"
[[ -n "$ARG_TRASH" ]] && echo "TRASH:$ARG_TRASH" >> "$livefile"
[[ -n "$ARG_ALLOWED" ]] && echo "ALLOWED:$ARG_ALLOWED" >> "$livefile"
[[ -n "$ARG_COMMAND" ]] && echo "COMMAND:$ARG_COMMAND" >> "$livefile"
[[ "$ARG_DRY_RUN" == "true" ]] && echo "DRY_RUN:true" >> "$livefile"
[[ -n "$ARG_STAT_KEYS" ]] && echo "STAT_KEYS:$ARG_STAT_KEYS" >> "$livefile"
[[ -n "$ARG_STAT_TEMPLATE" ]] && echo "STAT_TEMPLATE:$ARG_STAT_TEMPLATE" >> "$livefile"
[[ "$ARG_DISABLE_STATS" == "true" ]] && echo "DISABLE_STATS:true" >> "$livefile"
[[ "$ARG_STOP_NEXT_DAY" == "true" ]] && echo "STOP_NEXT_DAY:true" >> "$livefile"
[[ -n "$ARG_AUTOSAVE" ]] && echo "AUTOSAVE:$ARG_AUTOSAVE" >> "$livefile"
[[ "$ARG_DASHBOARD" == "true" ]] && echo "DASHBOARD:true" >> "$livefile"
[[ -n "$ARG_DASHBOARD_PORT" ]] && echo "DASHBOARD_PORT:$ARG_DASHBOARD_PORT" >> "$livefile"
[[ "$ARG_LEGACY_MODE" == "true" ]] && echo "LEGACY_MODE:true" >> "$livefile"
[[ "$ARG_VERSION" == "true" ]] && echo "VERSION:true" >> "$livefile"
history_init "$SN"
tmpdata=$(concat_lines "$livefile")
[[ -n "$tmpdata" ]] && history_add "$tmpdata"

# Execute the actual command
PYTHON="$SM_PATH/v2/.venv/bin/python3"
if [[ ! -x "$PYTHON" ]]; then
	echo "Error: Virtual environment not found at $SM_PATH/v2/.venv" >&2
	echo "Install with: cd $SM_PATH/v2 && python3 -m venv .venv && .venv/bin/pip install -e ." >&2
	exit 1
fi
$PYTHON -m fwtrash.cli.main run "${ARGS[@]}"
exit $?
