#!/bin/bash
#
# LOK Framework: submodule-generate.sh
# Generate wrapper scripts, symlinks, and help files for submodules.
#
# Usage:
#   ./src/submodule-generate.sh [CATEGORY]
#
# If CATEGORY is omitted, it scans all uppercase category directories.
#
# For each submodule directory containing .lok.conf and .lok.d/*.conf,
# it generates:
#   - CATEGORY/<tool>.sh      (wrapper script)
#   - CATEGORY/<tool>         (symlink to wrapper)
#   - CATEGORY/help_for_<tool>.txk  (basic help file)
#

PRE=$(dirname $(dirname $(realpath $0)))"/"
source $PRE'src/prepare.sh'
source $PRE'src/submodule.sh'

# Generate wrapper script from spec
generate_wrapper() {
	local category=$1
	local sm_dir=$2
	local sm_name=$3
	local sm_url=$4
	local sm_type=$5
	local spec_file=$6
	local tool_name=""
	local entry=""
	local description=""
	local pca_on_none="true"
	local -a pca_list=()
	local -a arg_defs=()
	
	# Parse spec file
	while IFS=':' read -r key value; do
		[[ -z "$key" || "$key" == \#* ]] && continue
		key=$(echo "$key" | tr -d ' ')
		value=$(echo "$value" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
		case "$key" in
			NAME) tool_name="$value" ;;
			ENTRY) entry="$value" ;;
			DESCRIPTION) description="$value" ;;
			PCA_ON_NONE_HELP) pca_on_none="$value" ;;
			ARG)
				# value format: VAR:SHORT:LONG:HAS_VALUE
				arg_defs+=("$value")
				local var=$(echo "$value" | cut -d':' -f1)
				pca_list+=("$var")
				;;
		esac
	done < "$spec_file"
	
	[[ -z "$tool_name" ]] && { echo "Error: missing NAME in $spec_file"; return 1; }
	[[ -z "$entry" ]] && { echo "Error: missing ENTRY in $spec_file"; return 1; }
	
	local wrapper="$PRE$category/$tool_name.sh"
	local symlink="$PRE$category/$tool_name"
	
	# Build PCA declarations
	local pca_decl="PCA=("
	for v in "${pca_list[@]}"; do
		pca_decl="$pca_decl\"$v\" "
	done
	pca_decl="$pca_decl)"
	
	# Build ARG_* and *_SHORT_ARG / *_ARG / *_VAL declarations
	local arg_decls=""
	for def in "${arg_defs[@]}"; do
		local var=$(echo "$def" | cut -d':' -f1)
		local short=$(echo "$def" | cut -d':' -f2)
		local long=$(echo "$def" | cut -d':' -f3)
		local hasval=$(echo "$def" | cut -d':' -f4)
		
		if [[ "$hasval" == "true" ]]; then
			arg_decls="${arg_decls}ARG_$var=\"\"\n"
		else
			arg_decls="${arg_decls}ARG_$var=false\n"
		fi
		arg_decls="${arg_decls}ARG_${var}_STRING=true\n"
		if [[ -n "$short" ]]; then
			arg_decls="${arg_decls}${var}_SHORT_ARG=\"$short\"\n"
		fi
		arg_decls="${arg_decls}${var}_ARG=\"$long\"\n"
		arg_decls="${arg_decls}${var}_VAL=$hasval\n"
		arg_decls="${arg_decls}\n"
	done
	
	# Build args construction
	local build_args=""
	for def in "${arg_defs[@]}"; do
		local var=$(echo "$def" | cut -d':' -f1)
		local short=$(echo "$def" | cut -d':' -f2)
		local long=$(echo "$def" | cut -d':' -f3)
		local hasval=$(echo "$def" | cut -d':' -f4)
		
		local flag="$short"
		[[ -z "$flag" ]] && flag="$long"
		if [[ "$hasval" == "true" ]]; then
			build_args="${build_args}[[ -n \"\$ARG_$var\" ]] && ARGS+=(\"$flag\" \"\$ARG_$var\")\n"
		else
			build_args="${build_args}[[ \"\$ARG_$var\" == \"true\" ]] && ARGS+=(\"$flag\")\n"
		fi
	done
	
	# Build config writing
	local write_config=""
	for def in "${arg_defs[@]}"; do
		local var=$(echo "$def" | cut -d':' -f1)
		local hasval=$(echo "$def" | cut -d':' -f4)
		
		if [[ "$hasval" == "true" ]]; then
			write_config="${write_config}[[ -n \"\$ARG_$var\" ]] && echo \"$var:\$ARG_$var\" >> \"\$livefile\"\n"
		else
			write_config="${write_config}[[ \"\$ARG_$var\" == \"true\" ]] && echo \"$var:true\" >> \"\$livefile\"\n"
		fi
	done
	
	# Create wrapper script
	cat > "$wrapper" <<EOF
#!/bin/bash
# $tool_name - $description (LoK wrapper)
# Accessible as: lok $category $tool_name RUN or directly as $tool_name
# Auto-generated by src/submodule-generate.sh

PRE=\$(dirname \$(realpath \$0))"/../"
source \$PRE'src/prepare.sh'
source \$PRE'src/history.sh'
source \$PRE'src/submodule.sh'

SM_PATH="\$PRE/$category/$sm_name"
SN="$tool_name"

$pca_decl

PCA_ON_NONE_HELP=$pca_on_none

$(echo -e "$arg_decls")
# Special flags handled before PCA
for arg in "\$@"; do
	case "\$arg" in
		-HH|--HH)
			history_init "\$SN"
			history_list
			exit 0
			;;
		--tool-help)
			if submodule_check "\$SM_PATH"; then
				export PYTHONPATH="\$SM_PATH:\$PYTHONPATH"
				exec python3 "\$SM_PATH/$entry" --help
			else
				echo "Error: Submodule '$sm_name' is not installed." >&2
				exit 1
			fi
			;;
	esac
done

source \$PRE'src/pca.sh'

# Check if submodule is installed
if ! submodule_check "\$SM_PATH"; then
	submodule_get_config "\$SM_PATH" 2>/dev/null
	submodule_prompt "\${SM_NAME:-$sm_name}" "\${SM_URL:-$sm_url}" "\$SM_PATH"
	[[ \$? -ne 0 ]] && exit 1
	if ! submodule_check "\$SM_PATH"; then
		echo "Error: Submodule still not available after install attempt." >&2
		exit 1
	fi
fi

# Build args from PCA variables
ARGS=()
$(echo -e "$build_args")
# Also pass any raw arguments from command line (direct invocation, non-PCA flags)
if [[ \${#PCA[@]} -eq 0 ]]; then
	for arg in "\$@"; do
		case "\$arg" in
			-RR|-Y|--run_config) continue ;;
			*) ARGS+=("\$arg") ;;
		esac
	done
fi

# Initialize history
livedir="\$DL/$category/\$SN"
livefile="\$livedir/config"
if [[ ! -d "\$livedir" ]]; then
	mkdir -p "\$livedir"
fi

: > "\$livefile"
$(echo -e "$write_config")
history_init "\$SN"
tmpdata=\$(concat_lines "\$livefile")
[[ -n "\$tmpdata" ]] && history_add "\$tmpdata"

# Execute the actual command
export PYTHONPATH="\$SM_PATH:\$PYTHONPATH"
python3 "\$SM_PATH/$entry" "\${ARGS[@]}"
exit \$?
EOF
	
	chmod +x "$wrapper"
	
	# Create or update symlink
	if [[ -L "$symlink" ]]; then
		rm "$symlink"
	elif [[ -e "$symlink" ]]; then
		echo "Warning: $symlink exists and is not a symlink. Skipping."
		return 1
	fi
	ln -s "$tool_name.sh" "$symlink"
	
	# Generate basic help file if missing
	local helpfile="$PRE$category/help_for_$tool_name.txk"
	if [[ ! -f "$helpfile" ]]; then
		cat > "$helpfile" <<EOF
$tool_name ($category/$tool_name.sh) - $description

Usage:
  $tool_name [options]
  lok $category $tool_name RUN [options]

Special flags:
  -h, --help        Show this LoK/PCA framework help
  -HH, --HH         Show run history for this tool
  --tool-help       Show the real submodule tool's help

$(if [[ ${#arg_defs[@]} -gt 0 ]]; then
  echo "Options:"
  for def in "${arg_defs[@]}"; do
    _var=$(echo "$def" | cut -d':' -f1)
    _short=$(echo "$def" | cut -d':' -f2)
    _long=$(echo "$def" | cut -d':' -f3)
    echo "  ${_short:+$_short, }$_long"
  done
fi)
EOF
	fi
	
	echo "Generated: $wrapper -> $symlink"
}

# Main
categories=()
if [[ -n "$1" ]]; then
	categories=("$1")
else
	for dir in "$PRE"[A-Z]*/; do
		[[ -d "$dir" ]] && categories+=("$(basename "$dir")")
	done
fi

for category in "${categories[@]}"; do
	[[ "$category" == "src" ]] && continue
	[[ ! -d "$PRE$category" ]] && continue
	
	# Find submodule directories
	for sm_dir in "$PRE$category"/*; do
		[[ ! -d "$sm_dir" ]] && continue
		[[ -L "$sm_dir" ]] && continue
		
		conf="$sm_dir/.lok.conf"
		specs_dir="$sm_dir/.lok.d"
		[[ ! -f "$conf" ]] && continue
		[[ ! -d "$specs_dir" ]] && continue
		
		sm_name=""
		sm_url=""
		sm_type=""
		
		while IFS=':' read -r key value; do
			[[ -z "$key" || "$key" == \#* ]] && continue
			key=$(echo "$key" | tr -d ' ')
			value=$(echo "$value" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
			case "$key" in
				NAME) sm_name="$value" ;;
				URL) sm_url="$value" ;;
				TYPE) sm_type="$value" ;;
			esac
		done < "$conf"
		
		[[ -z "$sm_name" ]] && { echo "Warning: missing NAME in $conf"; continue; }
		
		echo "Generating wrappers for submodule: $category/$sm_name"
		for spec in "$specs_dir"/*.conf; do
			[[ -f "$spec" ]] || continue
			generate_wrapper "$category" "$sm_dir" "$sm_name" "$sm_url" "$sm_type" "$spec"
		done
	done
done

echo "Done."
